appname: envelope-api
image: ghcr.io/ufuk-cetinkaya/envelope-api:latest
replicas: 1
job:
  enabled: false
service:
  enabled: true
secret:
  enabled: true
  constr: Server=mssql-server;Database=EBelgeDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
config:
  enabled: false
