appname: signer-ws
image: ghcr.io/ufuk-cetinkaya/signer-ws:latest
replicas: 1
dbname: ebelgedb
ingress:
  enabled: false
job:
  enabled: false
service:
  enabled: true
secret:
  enabled: false
config:
  enabled: false