appname: gibuser-api
image: ghcr.io/ufuk-cetinkaya/gib-user-api:latest
replicas: 1
dbname: ebelgedb
job:
  enabled: true
service:
  enabled: true
secret:
  enabled: true
  constr: Server=mssql-server;Database=GibUserDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
config:
  enabled: false
