appname: report-worker
image: ghcr.io/ufuk-cetinkaya/report-worker:latest
replicas: 1
dbname: gibuserdb
ingress:
  enabled: false
job:
  enabled: false
service:
  enabled: false
secret:
  enabled: true
  constr: Server=mssql-server.mssql-server.svc.cluster.local,1433;Database=EBelgeDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
config:
  enabled: true
configData:
  AppSettings__EArsivUrl: "https://test.efatura.gov.tr/earsiv/services1/EArsivWsPort"
  AppSettings__SignerUrl: "http://signer-ws.signer-ws.svc.cluster.local/signerws"
  AppSettings__DocumentApiUrl: "https://api.ufukcetinkaya.net/document"
  AppSettings__EntegratorVkn: "12345678917"
