appname: gibuser-worker
image: ghcr.io/ufuk-cetinkaya/gib-user-worker:latest
replicas: 0
job:
  enabled: false
service:
  enabled: false
secret:
  enabled: true
  constr: Server=mssql-server;Database=GibUserDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
config:
  enabled: true
configData:
  AppSettings__GbListUrl: https://merkeztest.gib.gov.tr/EFaturaMerkez/newUserGbListxml.zip
  AppSettings__PkListUrl: https://merkeztest.gib.gov.tr/EFaturaMerkez/newUserPkListxml.zip
