
services:
  envelope-worker:
    image: ghcr.io/ufuk-cetinkaya/envelope-worker:latest
    container_name: envelope-worker
    networks:
    - edonusum
    env_file:
    - .env

networks:
  edonusum:
    external: true