{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
  - port: 80
    targetPort: 8080
{{- end }}