{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.dbname }}-migration
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        args: ["migrate"]
        envFrom:
        - secretRef:
            name: {{ .Values.appname }}-secret
      restartPolicy: Never
{{- end}}