{{- if or .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.secret.constr }}
{{- end }}