apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.appname }}-external
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ .Values.appname }}
  externalSecretSpec:
    refreshInterval: "1h"
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: {{ .Values.appname }}-secret
      creationPolicy: Owner
    data:
    - secretKey: ConnectionStrings__DefaultConnection
      remoteRef:
        key: {{ .Values.dbname }}
        property: constr