apiVersion: batch/v1
kind: Job
metadata:
  name: gibuser-api-job
spec:
  template:
    spec:
      containers:
      - name: gibuser-api
        image: ghcr.io/ufuk-cetinkaya/gib-user-api:latest
        imagePullPolicy: IfNotPresent
        args: ["migrate"]
        envFrom:
        - secretRef:
            name: gibuser-api-secret
      restartPolicy: Never