apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Server=mssql-server.mssql-server.svc.cluster.local,1433;Database=UserDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
