
services:
  report-worker:
    image: ghcr.io/ufuk-cetinkaya/report-worker:latest
    container_name: report-worker
    networks:
    - edonusum
    env_file:
    - .env

networks:
  edonusum:
    external: true