apiVersion: v1
kind: ConfigMap
metadata:
  name: envelope-worker-config
data:
  AppSettings__EFaturaUrl: "https://merkeztest.gib.gov.tr/EFaturaMerkez/services1/EFatura"
  AppSettings__GibUserUrl: "http://gibuser-api.gibuser-api.svc.cluster.local"
  AppSettings__SignerUrl: "http://signer-ws.signer-ws.svc.cluster.local/signerws"