apiVersion: batch/v1
kind: Job
metadata:
  name: envelope-worker-job
spec:
  template:
    spec:
      containers:
      - name: envelope-worker
        image: ghcr.io/ufuk-cetinkaya/envelope-worker:latest
        imagePullPolicy: IfNotPresent
        args: ["migrate"]
        envFrom:
        - secretRef:
            name: envelope-worker-secret
      restartPolicy: Never