apiVersion: v1
kind: Secret
metadata:
  name: gibuserdb-secret
  namespace: edonusum
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Server=mssql-server;Database=GibUserDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
