apiVersion: v1
kind: ConfigMap
metadata:
  name: report-worker-config
data:
  AppSettings__EArsivUrl: "https://test.efatura.gov.tr/earsiv/services1/EArsivWsPort"
  AppSettings__SignerUrl: "http://signer-ws.signer-ws.svc.cluster.local/signerws"
  AppSettings__DocumentApiUrl: "https://api.ufukcetinkaya.net/document"
  AppSettings__EntegratorVkn: "12345678917"